services:
  app:
    build:
      context: ./docker/app
    user: "${UID:-1000}:${GID:-1000}"   # run php-fpm as host user
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html             # code lives in ./src
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
