services:
  app:
    build:
      context: ./docker/app
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on: []  # no db

  web:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
